In [1]:
import numpy as np
import MDP
import RL


''' Construct simple MDP as described in Lecture 2a Slides 13-14'''
T = np.array([[[0.5,0.5,0,0],[0,1,0,0],[0.5,0.5,0,0],[0,1,0,0]],[[1,0,0,0],[0.5,0,0,0.5],[0.5,0,0.5,0],[0,0,0.5,0.5]]])
R = np.array([[0,0,10,10],[0,0,10,10]])
discount = 0.9
mdp = MDP.MDP(T,R,discount)
rlProblem = RL.RL(mdp,np.random.normal)

### Question 0
The following cell shows the results of running tabular Q-learning for $1000$ episodes with $100$ steps in each episode with $\epsilon=0.3$ greedy exploration. The results for $\epsilon=0.0$ and variable temperature are also shown for the simple company enrivonment. The Q-learning algorithm converges to the same policy as developed in Part 1 of this assignment.

In [2]:
# Test Q-learning
[Q,policy] = rlProblem.qLearning(s0=0,initialQ=np.zeros([mdp.nActions,mdp.nStates]),nEpisodes=1000,nSteps=100,epsilon=0.3)
print ("\nQ-learning results: epsilon=0.3")
print (Q)
print (policy)
[Q,policy] = rlProblem.qLearning(s0=0,initialQ=np.zeros([mdp.nActions,mdp.nStates]),nEpisodes=1000,nSteps=100,epsilon=0., temperature=100)
print ("\nQ-learning results: temperature=100")
print (Q)
print (policy)
[Q,policy] = rlProblem.qLearning(s0=0,initialQ=np.zeros([mdp.nActions,mdp.nStates]),nEpisodes=1000,nSteps=100,epsilon=0., temperature=1000)
print ("\nQ-learning results: temperature=1000")
print (Q)
print (policy)


Q-learning results: epsilon=0.3
[[ 18.04773954  21.32905322  28.07905934  31.25061862]
 [ 14.82172089  25.14879854  30.71489705  40.98828559]]
[0 1 1 1]

Q-learning results: temperature=100
[[ 17.49778119  20.55329723  27.49805104  30.57447614]
 [ 14.41344503  24.48264398  29.94082703  40.05845558]]
[0 1 1 1]

Q-learning results: temperature=1000
[[ 17.56467717  20.84770078  27.70804399  30.86013875]
 [ 14.33652338  24.81332176  30.20010912  40.47566243]]
[0 1 1 1]
