In [1]:
import numpy as np
import MDP
import sys

''' Construct a simple maze MDP

  Grid world layout:

  ---------------------
  |  0 |  1 |  2 |  3 |
  ---------------------
  |  4 |  5 |  6 |  7 |
  ---------------------
  |  8 |  9 | 10 | 11 |
  ---------------------
  | 12 | 13 | 14 | 15 |
  ---------------------

  Goal state: 15
  Bad state: 9
  End state: 16

  The end state is an absorbing state that the agent transitions
  to after visiting the goal state.

  There are 17 states in total (including the end state)
  and 4 actions (up, down, left, right).'''

# Transition function: |A| x |S| x |S'| array
T = np.zeros([4,17,17])
a = 0.8;  # intended move
b = 0.1;  # lateral move

# up (a = 0)

T[0,0,0] = a+b;
T[0,0,1] = b;

T[0,1,0] = b;
T[0,1,1] = a;
T[0,1,2] = b;

T[0,2,1] = b;
T[0,2,2] = a;
T[0,2,3] = b;

T[0,3,2] = b;
T[0,3,3] = a+b;

T[0,4,4] = b;
T[0,4,0] = a;
T[0,4,5] = b;

T[0,5,4] = b;
T[0,5,1] = a;
T[0,5,6] = b;

T[0,6,5] = b;
T[0,6,2] = a;
T[0,6,7] = b;

T[0,7,6] = b;
T[0,7,3] = a;
T[0,7,7] = b;

T[0,8,8] = b;
T[0,8,4] = a;
T[0,8,9] = b;

T[0,9,8] = b;
T[0,9,5] = a;
T[0,9,10] = b;

T[0,10,9] = b;
T[0,10,6] = a;
T[0,10,11] = b;

T[0,11,10] = b;
T[0,11,7] = a;
T[0,11,11] = b;

T[0,12,12] = b;
T[0,12,8] = a;
T[0,12,13] = b;

T[0,13,12] = b;
T[0,13,9] = a;
T[0,13,14] = b;

T[0,14,13] = b;
T[0,14,10] = a;
T[0,14,15] = b;

T[0,15,16] = 1;
T[0,16,16] = 1;

# down (a = 1)

T[1,0,0] = b;
T[1,0,4] = a;
T[1,0,1] = b;

T[1,1,0] = b;
T[1,1,5] = a;
T[1,1,2] = b;

T[1,2,1] = b;
T[1,2,6] = a;
T[1,2,3] = b;

T[1,3,2] = b;
T[1,3,7] = a;
T[1,3,3] = b;

T[1,4,4] = b;
T[1,4,8] = a;
T[1,4,5] = b;

T[1,5,4] = b;
T[1,5,9] = a;
T[1,5,6] = b;

T[1,6,5] = b;
T[1,6,10] = a;
T[1,6,7] = b;

T[1,7,6] = b;
T[1,7,11] = a;
T[1,7,7] = b;

T[1,8,8] = b;
T[1,8,12] = a;
T[1,8,9] = b;

T[1,9,8] = b;
T[1,9,13] = a;
T[1,9,10] = b;

T[1,10,9] = b;
T[1,10,14] = a;
T[1,10,11] = b;

T[1,11,10] = b;
T[1,11,15] = a;
T[1,11,11] = b;

T[1,12,12] = a+b;
T[1,12,13] = b;

T[1,13,12] = b;
T[1,13,13] = a;
T[1,13,14] = b;

T[1,14,13] = b;
T[1,14,14] = a;
T[1,14,15] = b;

T[1,15,16] = 1;
T[1,16,16] = 1;

# left (a = 2)

T[2,0,0] = a+b;
T[2,0,4] = b;

T[2,1,1] = b;
T[2,1,0] = a;
T[2,1,5] = b;

T[2,2,2] = b;
T[2,2,1] = a;
T[2,2,6] = b;

T[2,3,3] = b;
T[2,3,2] = a;
T[2,3,7] = b;

T[2,4,0] = b;
T[2,4,4] = a;
T[2,4,8] = b;

T[2,5,1] = b;
T[2,5,4] = a;
T[2,5,9] = b;

T[2,6,2] = b;
T[2,6,5] = a;
T[2,6,10] = b;

T[2,7,3] = b;
T[2,7,6] = a;
T[2,7,11] = b;

T[2,8,4] = b;
T[2,8,8] = a;
T[2,8,12] = b;

T[2,9,5] = b;
T[2,9,8] = a;
T[2,9,13] = b;

T[2,10,6] = b;
T[2,10,9] = a;
T[2,10,14] = b;

T[2,11,7] = b;
T[2,11,10] = a;
T[2,11,15] = b;

T[2,12,8] = b;
T[2,12,12] = a+b;

T[2,13,9] = b;
T[2,13,12] = a;
T[2,13,13] = b;

T[2,14,10] = b;
T[2,14,13] = a;
T[2,14,14] = b;

T[2,15,16] = 1;
T[2,16,16] = 1;

# right (a = 3)

T[3,0,0] = b;
T[3,0,1] = a;
T[3,0,4] = b;

T[3,1,1] = b;
T[3,1,2] = a;
T[3,1,5] = b;

T[3,2,2] = b;
T[3,2,3] = a;
T[3,2,6] = b;

T[3,3,3] = a+b;
T[3,3,7] = b;

T[3,4,0] = b;
T[3,4,5] = a;
T[3,4,8] = b;

T[3,5,1] = b;
T[3,5,6] = a;
T[3,5,9] = b;

T[3,6,2] = b;
T[3,6,7] = a;
T[3,6,10] = b;

T[3,7,3] = b;
T[3,7,7] = a;
T[3,7,11] = b;

T[3,8,4] = b;
T[3,8,9] = a;
T[3,8,12] = b;

T[3,9,5] = b;
T[3,9,10] = a;
T[3,9,13] = b;

T[3,10,6] = b;
T[3,10,11] = a;
T[3,10,14] = b;

T[3,11,7] = b;
T[3,11,11] = a;
T[3,11,15] = b;

T[3,12,8] = b;
T[3,12,13] = a;
T[3,12,12] = b;

T[3,13,9] = b;
T[3,13,14] = a;
T[3,13,13] = b;

T[3,14,10] = b;
T[3,14,15] = a;
T[3,14,14] = b;

T[3,15,16] = 1;
T[3,16,16] = 1;

# Reward function: |A| x |S| array
R = -1 * np.ones([4,17]);

# set rewards
R[:,15] = 100;  # goal state
R[:,9] = -70;   # bad state
R[:,16] = 0;    # end state

# Discount factor: scalar in [0,1)
discount = 0.95

# MDP object
mdp = MDP.MDP(T,R,discount)

### Question 1:

In [3]:
'''Test each procedure'''
[V,nIterations,epsilon] = mdp.valueIteration(initialV=np.zeros(mdp.nStates),tolerance=0.01)
policy = mdp.extractPolicy(V)
print ("------------------------ tolerance:0.01 ---------------------------")
print ("[DEBUG] valueIteration nIterations: {}, epsilon: {}".format(nIterations,epsilon))
print ("policy:")
print (policy)
print ("V:")
print (V)
[V,nIterations,epsilon] = mdp.valueIteration(initialV=np.zeros(mdp.nStates),tolerance=0.0)
policy = mdp.extractPolicy(V)
print ("------------------------ tolerance:0.0 ---------------------------")
print ("[DEBUG] valueIteration nIterations: {}, epsilon: {}".format(nIterations,epsilon))
print ("policy:")
print (policy)
print ("V:")
print (V)

------------------------ tolerance:0.01 ---------------------------
[DEBUG] valueIteration nIterations: 20, epsilon: 0.008079508521525725
policy:
[3 3 3 1 3 3 3 1 1 3 3 1 3 3 3 0 0]
V:
[  60.62388836   66.03486523   71.80422632   77.09196339   59.81429704
   65.18237783   77.83066489   84.14118981   58.09361039    7.98780239
   84.86704922   91.78159355   69.49584217   76.80962081   91.78159355
  100.            0.        ]
------------------------ tolerance:0.0 ---------------------------
[DEBUG] valueIteration nIterations: 62, epsilon: 0.0
policy:
[3 3 3 1 3 3 3 1 1 3 3 1 3 3 3 0 0]
V:
[  60.63256172   66.03897428   71.8062328    77.09295576   59.81945165
   65.18457679   77.83151901   84.14149059   58.0955782     7.98862928
   84.86730581   91.78165089   69.4968138    76.80991653   91.78165089
  100.            0.        ]


### Question 2:

In [4]:
[policy,V,nIterations] = mdp.policyIteration(np.zeros(mdp.nStates,dtype=int))
print ("----------------------------------------------------------------")
print ("[DEBUG] policyIteration nIterations: {}".format(nIterations))
print ("policy:")
print (policy)
print ("V:")
print (V)

----------------------------------------------------------------
[DEBUG] policyIteration nIterations: 5
policy:
[3 3 3 1 3 3 3 1 1 3 3 1 3 3 3 0 0]
V:
[  60.63256172   66.03897428   71.8062328    77.09295576   59.81945165
   65.18457679   77.83151901   84.14149059   58.0955782     7.98862928
   84.86730581   91.78165089   69.4968138    76.80991653   91.78165089
  100.            0.        ]


### Question 3:

In [6]:
[policy,V,nIterations,epsilon] = mdp.modifiedPolicyIteration(np.zeros(mdp.nStates,dtype=int),np.zeros(mdp.nStates),tolerance=0.01)
print ("--------------------------- Original ------------------------------")
print ("[DEBUG] modifiedPolicyIteration nIterations: {}, epsilon: {}".format(nIterations,epsilon))
print ("policy:")
print (policy)
print ("V:")
print (V)
#policy iteration using modified policy iteration
[policy,V,nIterations,epsilon] = mdp.modifiedPolicyIteration(np.zeros(mdp.nStates,dtype=int),np.zeros(mdp.nStates),tolerance=0.0,nEvalIterations=np.inf)
print ("------------------------ nEvalIterations:inf ----------------------")
print ("[DEBUG] modifiedPolicyIteration nIterations: {}, epsilon: {}".format(nIterations,epsilon))
print ("policy:")
print (policy)
print ("V:")
print (V)
#value iteration using modified policy iteration
[policy,V,nIterations,epsilon] = mdp.modifiedPolicyIteration(np.zeros(mdp.nStates,dtype=int),np.zeros(mdp.nStates),tolerance=0.01,nEvalIterations=0)
print ("------------------------ nEvalIterations:0 ------------------------")
print ("[DEBUG] modifiedPolicyIteration nIterations: {}, epsilon: {}".format(nIterations,epsilon))
print ("policy:")
print (policy)
print ("V:")
print (V)
[policy,V,nIterations,epsilon] = mdp.modifiedPolicyIteration(np.zeros(mdp.nStates,dtype=int),np.zeros(mdp.nStates),tolerance=0.0,nEvalIterations=0)
print ("------------------ nEvalIterations:0,tolerenace:0.0 ---------------")
print ("[DEBUG] modifiedPolicyIteration nIterations: {}, epsilon: {}".format(nIterations,epsilon))
print ("policy:")
print (policy)
print ("V:")
print (V)

--------------------------- Original ------------------------------
[DEBUG] modifiedPolicyIteration nIterations: 6, epsilon: 0.004589924537079071
policy:
[3 3 3 1 3 3 3 1 1 3 3 1 3 3 3 0 0]
V:
[  60.62299224   66.03435705   71.80403745   77.09184077   59.81354253
   65.18219837   77.83055148   84.1411644    58.09343024    7.98767806
   84.86703052   91.78158579   69.49571217   76.80959703   91.78158579
  100.            0.        ]
------------------------ nEvalIterations:inf ----------------------
[DEBUG] modifiedPolicyIteration nIterations: 5, epsilon: 0.0
policy:
[3 3 3 1 3 3 3 1 1 3 3 1 3 3 3 0 0]
V:
[  60.63256172   66.03897428   71.8062328    77.09295576   59.81945165
   65.18457679   77.83151901   84.14149059   58.0955782     7.98862928
   84.86730581   91.78165089   69.4968138    76.80991653   91.78165089
  100.            0.        ]
------------------------ nEvalIterations:0 ------------------------
[DEBUG] modifiedPolicyIteration nIterations: 20, epsilon: 0.00807950852152572

In [12]:
#this cell counts the number of policy iteration steps required
nIterations_list = []
for nEvalIterations in range(1, 11):
    [policy,V,nIterations,epsilon] = mdp.modifiedPolicyIteration(np.zeros(mdp.nStates,dtype=int),np.zeros(mdp.nStates),nEvalIterations=nEvalIterations,tolerance=0.01)
    nIterations_list.append(nIterations)
    #print ("nEvalIterations: {}, nIterations: {}".format(nEvalIterations, nIterations))
    print ("---------------------- nEvalIterations: {} ---------------------".format(nEvalIterations))
    print ("[DEBUG] modifiedPolicyIteration nIterations: {}, epsilon: {}".format(nIterations,epsilon))
    print ("policy:")
    print (policy)
    print ("V:")
    print (V)
print ("nIterations List: {}".format(nIterations_list))

---------------------- nEvalIterations: 1 ---------------------
[DEBUG] modifiedPolicyIteration nIterations: 11, epsilon: 0.0027812914590654714
policy:
[3 3 3 1 3 3 3 1 1 3 3 1 3 3 3 0 0]
V:
[  60.62684254   66.03625179   71.80491036   77.09229804   59.81602563
   65.18313123   77.83095193   84.14129267   58.09428458    7.98807868
   84.86713734   91.78161279   69.49616973   76.80972221   91.78161279
  100.            0.        ]
---------------------- nEvalIterations: 2 ---------------------
[DEBUG] modifiedPolicyIteration nIterations: 8, epsilon: 0.0032342488432277605
policy:
[3 3 3 1 3 3 3 1 1 3 3 1 3 3 3 0 0]
V:
[  60.62585588   66.03575432   71.80468363   77.09217736   59.81537412
   65.18289152   77.83084576   84.14125941   58.0940612     7.98797218
   84.86710983   91.78160561   69.49604825   76.80969016   91.78160561
  100.            0.        ]
---------------------- nEvalIterations: 3 ---------------------
[DEBUG] modifiedPolicyIteration nIterations: 7, epsilon: 0.0031580695

In [13]:
#this cell counts the total number of steps required (policy iteration + value function evaluation)
nIterations_full_list = []
for nEvalIterations in range(1, 11):
    [policy,V,nIterations,epsilon] = mdp.modifiedPolicyIteration(np.zeros(mdp.nStates,dtype=int),np.zeros(mdp.nStates),nEvalIterations=nEvalIterations,tolerance=0.01, report_full_iter=True)
    nIterations_full_list.append(nIterations)
    #print ("nEvalIterations: {}, nIterations_all: {}".format(nEvalIterations, nIterations))
    print ("---------------------- nEvalIterations: {} ---------------------".format(nEvalIterations))
    print ("[DEBUG] modifiedPolicyIteration nIterations_all: {}, epsilon: {}".format(nIterations,epsilon))
    print ("policy:")
    print (policy)
    print ("V:")
    print (V)
print ("nIterations Complete List: {}".format(nIterations_full_list))

---------------------- nEvalIterations: 1 ---------------------
[DEBUG] modifiedPolicyIteration nIterations_all: 22, epsilon: 0.0027812914590654714
policy:
[3 3 3 1 3 3 3 1 1 3 3 1 3 3 3 0 0]
V:
[  60.62684254   66.03625179   71.80491036   77.09229804   59.81602563
   65.18313123   77.83095193   84.14129267   58.09428458    7.98807868
   84.86713734   91.78161279   69.49616973   76.80972221   91.78161279
  100.            0.        ]
---------------------- nEvalIterations: 2 ---------------------
[DEBUG] modifiedPolicyIteration nIterations_all: 24, epsilon: 0.0032342488432277605
policy:
[3 3 3 1 3 3 3 1 1 3 3 1 3 3 3 0 0]
V:
[  60.62585588   66.03575432   71.80468363   77.09217736   59.81537412
   65.18289152   77.83084576   84.14125941   58.0940612     7.98797218
   84.86710983   91.78160561   69.49604825   76.80969016   91.78160561
  100.            0.        ]
---------------------- nEvalIterations: 3 ---------------------
[DEBUG] modifiedPolicyIteration nIterations_all: 27, epsilon

The above cell shows the result of running Modified Policy Iteration with different values of `nEvalIterations`. `nIterations List`$=[11, 8, 7, 6, 6, 5, 5, 5, 5, 5]$ shows the number of iterations of policy iteration step which were executed. `nIterations Complete List`$=[22, 24, 27, 30, 33, 35, 40, 44, 48, 52]$ also includes the total number of value function evaluation steps which were executed alongside policy iteration steps. When `nEvalIterations=1`, the partial policy iteration only runs once and thus is not able to converge fast and thus we see that modified policy iteration takes 11 steps. As the value of `nEvalIterations` increases the number of policy iteration steps decreases quickly to 5. We see from `Q2` results that 5 is the least amount of steps required to converge to optimal policy and we won't get nIterations lower than 5. Looking at the output of `nIterations Complete List`, we see that even though the number of policy iteration steps stay constant at 5 for `nEvalIterations>5`, the total number of policy + value evaluation steps (almost linearly) keep increasing.
Looking at the running time of Modified Policy Iteration:
$$O(k|S|^2 + |S|^2|A|)$$
where k is the number of partial policy evaluations. From the above analysis it is important to run cross-validation techniques for hyper-parameter estimation for k. If k is too small, then we would run extra steps of policy iteration (which has a running time of cubic in the number of states per iteration) and if k is too large, then we would run extra steps of value function evaluation (which would result in $|S|^2|A|$ running time factor per iteration).